#spring:
#  application:
#    name: springboot-sundz
#  datasource:
#    db1:
#    url: jdbc:mysql://192.168.2.68:3306/cic?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&relaxAutoCommit=true&autoCommit=true&useSSL=false&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Parav1ew@
#    db2:
#      url: jdbc:mysql://192.168.2.68:3306/cic_fx?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&relaxAutoCommit=true&autoCommit=true&useSSL=false&serverTimezone=UTC
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: Parav1ew@
#    dbcp2:
#      platform: mysql
#      continue-on-error: true
#      sql-script-encoding: UTF-8
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      #transaction-isolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
#      maximum-pool-size: 15
#      minimum-idle: 5
#      jdbc-url: ${spring.datasource.url}
#      allow-pool-suspension: true
#      #isolate-internal-queries: true
#      auto-commit: true
#      #register-mbeans: true
#      idle-timeout: 300000
#      pool-name: DatebookHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 300000
#      connection-test-query: SELECT 1
