---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sundz.
--- DateTime: 2021/6/26 18:17
---


--[[for i = 0, 10, 1 do
    if i == 7 then
        print('Break跳出')
        break
    end
    print('i:' .. i)
end]]



function printStart()
    for i = 1, 7 do
        local s = ''
        for j = 1, i do
            s = s .. '*'
        end
        print(s)
    end
end

function hi(some)
    --[[    luajava.bindClass("com.sun.springbootdemo.entities.Pet")]]
    print("every day  is  a  new  day:" .. some)
end

a = { '1', '2', '3' }
print("------------------------lua end-----------------------------")

function javaObj()
    --[[    local pet = luajava.bindClass('com.sun.springbootdemo.entities.Pet')]]
    local pet = luajava.newInstance('com.sun.springbootdemo.entities.Pet', 'Tom')
    print(pet:getName())
end
